### ISSUE TITLE
Possible support for Jenkins Release Plugin

### ISSUE THREAD

**Issue by dlvenable** [researchgate/gradle-release#101]
The [Jenkins Release Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Release+Plugin) provides the ability to make a release in Jenkins. It does this by letting users add pre or post build steps. With it, you cannot reconfigure the normal build step. What do you think of adding two new tasks to the build - preRelease and postRelease?

Based on the list of steps from the README, it could break them up as follows:

Pre-Release
* The plugin checks for any un-committed files (Added, modified, removed, or un-versioned).
* Checks for any incoming or outgoing changes.
* Removes the SNAPSHOT flag on your projects version (If used)
* Prompts you for the release version.
* Checks if your project is using any SNAPSHOT dependencies

Normal Build
-------
* Will build your project.

Post Release
-------
* Commits the project if SNAPSHOT was being used.
* Creates a release tag with the current version.
* Prompts you for the next version.
* Commits the project with the new version.

**Comment by danez** [comment]
We also use the release plugin together with gradle-release. What we did is have just the pre build step like this:
```clean -Pgradle.release.useAutomaticVersion=true  -PnewVersion=${nextSnapshotVersion} -PreleaseVersion=${releaseVersion} release```

It is not the cleanest solution but it works in our case.

The problem with having two separate release steps (like the maven release plugin) is that these two would need to have some kind of temp storage between them to transfer things like "wasSnapshotUsed: yes/no" for example. Because this flag is detected in pre-release but then needed in post-release.

**Comment by dlvenable** [comment]
Thanks for letting me know how you do it, @danez. So if I understand, you perform the true release build in the pre-build step. Then the normal build runs on the next snapshot?

Do you think it would work if the post-build did the release rather than the pre-build?

**Comment by danez** [comment]
Exactly, that's the way it is done in our case, first release, then normal build again on the next snapshot.

I think it should also work the other way around: first do the normal build on the current snapshot and then do the full release in post-build.
