### ISSUE TITLE
Support for changelog update

### ISSUE THREAD

**Issue by gluck** [researchgate/gradle-release#151]
While there's (sadly) no standard for changelog formats, the [keepachangelog](http://keepachangelog.com) one is as close as we can get to one.

How about updating the CHANGELOG.md file (when this format is used) upon release ? Put the released version in place of the *Unreleased* place holder, insert the date, and create a new placeholder.

Any thoughts on that ? coz we think that could be cool :+1:

**Comment by muryoh** [comment]
I second this proposal, it would be really awesome :8ball:

**Comment by danez** [comment]
What exactly is this issue about? Changing the changelog file of this plugin to the structure you proposed?

Or the plugin should update the changelog of a project where the plugin is applied?

If you mean the first then i will respect the layout when i touch the changelog file the next time.
For the second one, I think this is out of scope for this plugin. I'm trying to only do one thing with this plugin and not multiple different things. But I agree that it would be nice to have such kind of functionality.

What I'm thinking about already since a longer time is an repository of different release-steps, which users can apply to there release. Plugins for the plugin :) But the top prio right now is getting the plugin work correctly with multi-project builds, so I won't have time to work on this.

**Comment by gluck** [comment]
It's about the later (although feel free to apply the format here as well). It's also not about asking you to do it, as we could contribute it, providing you agree with it.

We can also go the plugin of plugin way, would you consider PRs if some adjustments were required to integrate properly?

Thanks !

**Comment by marshallpierce** [comment]
I'd prefer to see the scope of this plugin limited to as little as possible. If other things want to hook in to that process that's fine, but I wouldn't use this.
