### ISSUE TITLE
3.0.0 - buildTasks default changed from ['build'] to []

### ISSUE THREAD

**Issue by grimsa** [researchgate/gradle-release#370]
See diff between 2.8.1 and 3.0.0: https://github.com/researchgate/gradle-release/compare/2.8.1...3.0.0#diff-ed58daee80000b4a55c5012beb76d51425a97554e223d04fc4501c708bb7f3fcR74-R76

Is this change intended?

`README.md` still lists `buildTasks = ['build']` as the default value.

Workaround - set the value explicitly in your build config:
```
release {
    buildTasks.set(List.of('build'))
}
```

**Comment by Hillkorn** [comment]
The reason I removed it is that is caused trouble in the past.
In case you have a multi project setup and the root doesn't contain any code because it's only used as a wrapper there is no build task by default. Also in case you have some project that doesn't use the gradle base plugin there might be no build task.
We could make a new feature with a default provider that is set as an convention and checks if the base plugin is present and then return the build task by default :thinking:
