### ISSUE TITLE
The execution gets stuck at checkUpdateNeeded task on a Windows 7 PC with git SCM

### ISSUE THREAD

**Issue by Zlate87** [researchgate/gradle-release#81]
When I try to run on a Windows 7 PC with git SCM the release execution gets stuck at checkUpdateNeeded task.

When I try the same on a Mac, there is no issue.

Looking at the debug messages, the last entry is:

     >>> Running [git, --git-dir=MY_WORKSPACE.git, --work-tree=MY_WORKSPACE, remote, update]

If I try to run `git remote update` directly I'm prompted for username and password, so it looks that the issue is because git is waiting for username and password, but the plugin is not asking you for them.

**Comment by segfly** [comment]
For me (also on Windows 7 using cygwin) `git remote update` was also hanging. I was using an SSH remote and as it turns out, I added my private key to Eclipse, but it was not in my `~/home/<user>/.ssh` directory. Once I added this, I [checked my ssh access](https://help.github.com/articles/generating-ssh-keys/#step-4-test-everything-out) from the command line and found the release plugin stopped hanging.

**Comment by crc83** [comment]
Got the same issue with Hudson and SVN

**Comment by bgroenks96** [comment]
Same problem on Linux Mint 17.3, git 1.9.1, gradle 2.10, release-plugin 2.3.5

Except mine doesn't hang. It just fails with the "badpublickey" error. It seems to have something to do with the fact that my RSA key requires a password.
